<?php
/**
 * Risecommerce  EmailAttachments
 *
 * PHP version 7
 *
 * @category Risecommerce
 * @package  Risecommerce_EmailAttachments
 * @author   Risecommerce <magento@risecommerce.com>
 * @license  https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link     https://www.risecommerce.com
 */


namespace Risecommerce\EmailAttachments\Model\Config\Backend;

use Magento\Framework\App\Config\Value;
use Magento\Framework\Exception\ValidatorException;

/**
 * Class Email
 * @package Risecommerce\EmailAttachments\Model\Config\Backend
 */
class Email extends Value
{
    /**
     * @return Value|void
     * @throws ValidatorException
     */
    public function beforeSave()
    {
        if (!empty($this->getValue())) {
            $valueArray = explode(',', $this->getValue());
            foreach ($valueArray as $value) {
                if (!filter_var($value, FILTER_VALIDATE_EMAIL)) {
                    throw new ValidatorException(__('Invalid email format.'));
                }
            }
        }
        parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}
